version: '3.7'

services:
  app:
    image: my-image-name:latest
    build:
      context: .
      dockerfile: VCC_Projekt/Dockerfile
    secrets:
      - VCC_DB_SERVER
      - VCC_DB_NAME
      - VCC_DB_USER
      - VCC_DB_PASSWORD
      - VCC_FRONTEND_URL
      - VCC_MAIL_EMAIL
      - VCC_MAIL_PASSWORD
      - VCC_TENANT_ID
      - VCC_CLIENT_ID
      - VCC_CLIENT_SECRET
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

secrets:
  VCC_DB_SERVER:
    external: true
  VCC_DB_NAME:
    external: true
  VCC_DB_USER:
    external: true
  VCC_DB_PASSWORD:
    external: true
  VCC_FRONTEND_URL:
    external: true
  VCC_MAIL_EMAIL:
    external: true
  VCC_MAIL_PASSWORD:
    external: true
  VCC_TENANT_ID:
    external: true
  VCC_CLIENT_ID:
    external: true
  VCC_CLIENT_SECRET:
    external: true
