version: '3.7'

services:
  vcc-app:
    image: ghcr.io/mirci212/vcc_projekt:latest
    ports:
      - "443:8081"
      - "80:8080"
    build:
      context: .
      dockerfile: VCC_Projekt/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_SERVER_FILE=/run/secrets/DB_SERVER
      - DB_NAME_FILE=/run/secrets/DB_NAME
      - DB_USER_FILE=/run/secrets/DB_USER
      - DB_PASSWORD_FILE=/run/secrets/DB_PASSWORD
      - FRONTEND_URL_FILE=/run/secrets/FRONTEND_URL
      - MAIL_EMAIL_FILE=/run/secrets/MAIL_EMAIL
      - MAIL_PASSWORD_FILE=/run/secrets/MAIL_PASSWORD
      - TENANT_ID_FILE=/run/secrets/TENANT_ID
      - CLIENT_ID_FILE=/run/secrets/CLIENT_ID
      - CLIENT_SECRET_FILE=/run/secrets/CLIENT_SECRET
      - SMTP_SERVER_FILE=/run/secrets/SMTP_SERVER      # Neu hinzugefügt
      - IMAP_SERVER_FILE=/run/secrets/IMAP_SERVER      # Neu hinzugefügt
    secrets:
      - DB_SERVER
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - FRONTEND_URL
      - MAIL_EMAIL
      - MAIL_PASSWORD
      - TENANT_ID
      - CLIENT_ID
      - CLIENT_SECRET
      - SMTP_SERVER                                   
      - IMAP_SERVER                                   

secrets:
  DB_SERVER:
    external: true
  DB_NAME:
    external: true
  DB_USER:
    external: true
  DB_PASSWORD:
    external: true
  FRONTEND_URL:
    external: true
  MAIL_EMAIL:
    external: true
  MAIL_PASSWORD:
    external: true
  TENANT_ID:
    external: true
  CLIENT_ID:
    external: true
  CLIENT_SECRET:
    external: true
  SMTP_SERVER:                                       
    external: true
  IMAP_SERVER:                                      
    external: true
