name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Write appsettings.json from secret
      run: |
        # Write the appsettings.json securely from the secret (ensure it's hidden)
        echo "${{ secrets.APPSETTINGS_JSON }}" | base64 --decode > VCC_Projekt/appsettings.json
      env:
        # Mask the secret to prevent it from appearing in the logs
        APPSETTINGS_JSON: ${{ secrets.APPSETTINGS_JSON }}

    - name: Build the Docker image
      run: docker build . --file VCC_Projekt/Dockerfile --tag my-image-name:latest

    - name: Clean up appsettings.json
      run: rm VCC_Projekt/appsettings.json
