name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Write appsettings.json from secret
      run: |
        echo "$APPSETTINGS_JSON" > VCC_Projekt/appsettings.json
      env:
        APPSETTINGS_JSON: ${{ secrets.APPSETTINGS_JSON }}

    - name: Generate timestamp tag
      id: tag
      run: |
        TAG=$(date +'%d.%m.%Y_%H-%M')
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "IMAGE_NAME=ghcr.io/mirci212/vcc_projekt:$TAG" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker build -f VCC_Projekt/Dockerfile -t ${{ env.IMAGE_NAME }} -t ghcr.io/mirci212/vcc_projekt:latest .

    - name: Log in to GitHub Container Registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin

    - name: Push the Docker image
      run: |
        docker push ${{ env.IMAGE_NAME }}
        docker push ghcr.io/mirci212/vcc_projekt:latest

    - name: Clean up appsettings.json
      run: rm VCC_Projekt/appsettings.json
