name: Docker Image CI

on:
  push:
    branches: ["master"]
    paths: ["VCC_Project/**"]  # Nur bei Änderungen im VCC_Project-Ordner auslösen
  pull_request:
    branches: ["master"]
    paths: ["VCC_Project/**"]
  workflow_dispatch:  # Erlaubt manuelles Auslösen über die GitHub UI
    inputs:
      tag_suffix:
        required: false
        default: "manual"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Change directory to VCC_Project
        run: cd VCC_Project

      - name: Build Docker image
        run: docker build -t my-vcc-image:$(date +%s) .
        working-directory: ./VCC_Project  # Stellt sicher, dass der Build im richtigen Ordner läuft
