name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        echo "$DOCKER_COMPOSE_YML" > docker-compose.yml
      env:
        DOCKER_COMPOSE_YML: ${{ secrets.DOCKER_COMPOSE_YML }}

    - name: Write appsettings.json from secret
      run: |
        echo "${{ secrets.APPSETTINGS_JSON }}" | base64 --decode > VCC_Projekt/appsettings.json
      env:
        APPSETTINGS_JSON: ${{ secrets.APPSETTINGS_JSON }}

    - name: Build the Docker image
      run: |
        docker-compose up -d --build

    - name: Clean up appsettings.json
      run: rm VCC_Projekt/appsettings.json
