name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Write appsettings.json from secret
      run: |
        echo "${{ secrets.APPSETTINGS_JSON }}" > VCC_Projekt/appsettings.json

    - name: Build the Docker image
      run: docker build . --file VCC_Projekt/Dockerfile --tag my-image-name:latest
