name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push latest
      run: |
        REPO=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        docker build -f VCC_Projekt/Dockerfile -t ghcr.io/$REPO:latest .
        docker push ghcr.io/$REPO:latest

