name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Write appsettings.json from secret
      run: |
        echo "$APPSETTINGS_JSON" > VCC_Projekt/appsettings.json
      env:
        APPSETTINGS_JSON: ${{ secrets.APPSETTINGS_JSON }}

    - name: Generate date tag
      run: |
        echo "DATE_TAG=$(date +'%d.%m.%Y_%H-%M')" >> $GITHUB_ENV

    - name: Login to GHCR
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and tag
      run: |
        docker build -f VCC_Projekt/Dockerfile \
          -t ghcr.io/mirci212/vcc_projekt:latest \
          -t ghcr.io/mirci212/vcc_projekt:${{ env.DATE_TAG }} .

    - name: Push images
      run: |
        docker push ghcr.io/mirci212/vcc_projekt:latest
        docker push ghcr.io/mirci212/vcc_projekt:${{ env.DATE_TAG }}

    - name: Clean up
      run: rm VCC_Projekt/appsettings.json
