name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Write appsettings.json from secret
      run: |
        echo "$APPSETTINGS_JSON" > VCC_Projekt/appsettings.json
      env:
        APPSETTINGS_JSON: ${{ secrets.APPSETTINGS_JSON }}

    - name: Generate timestamp tag
      id: tag
      run: |
        TAG=$(date +'%d.%m.%Y_%H-%M')
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "IMAGE_NAME=ghcr.io/mirci212/vcc_projekt:$TAG" >> $GITHUB_ENV

    - name: Build and push
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
        docker build -f VCC_Projekt/Dockerfile \
          -t ${{ env.IMAGE_NAME }} \
          -t ghcr.io/mirci212/vcc_projekt:latest .
        docker push --all-tags ghcr.io/mirci212/vcc_projekt

    - name: Clean up appsettings.json
      run: rm VCC_Projekt/appsettings.json
