name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Generate dynamic tag
      id: tag
      run: |
        echo "TAG=$(date +%Y%m%d_%H%M)" >> $GITHUB_ENV
        echo "IMAGE=ghcr.io/mirci212/vcc_projekt:$TAG" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: VCC_Projekt/Dockerfile
        push: true
        tags: ${{ env.IMAGE }}
        secrets: |
          "DB_SERVER=${{ secrets.DB_SERVER }}"
          "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
          # Fügen Sie hier alle anderen Secrets hinzu

    - name: Update compose file
      run: |
        sed -i "s|image: vcc_projekt:.*|image: ${{ env.IMAGE }}|" docker-compose.yml
        # Für Kubernetes:
        # sed -i "s|image:.*|image: ${{ env.IMAGE }}|" k8s/deployment.yaml

    - name: Deploy (example for SSH)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /path/to/your/project
          docker compose pull
          docker compose up -d
